import "./{styles}/globals.scss";
import "./{styles}/reset.scss";
import "./{styles}/buttons.scss";
import "./{styles}/fonts.scss";
import "./{styles}/variables.scss";
import "swiper/css";

import Header from "./{layouts}/header";
import Footer from "./{layouts}/footer";

export const metadata = {
  title: "IMA-Asia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
